### ISSUE TITLE
fails to build with ghc-9.6

### ISSUE THREAD

**Issue by juhp** [mstksg/functor-combinators#7]
```
       Building library for functor-combinators-0.4.1.2..                                                                           
                                                                                                                                    
       on the commandline: warning: [-Wdeprecated-flags]                                                                            
           -XTypeInType is deprecated: use -XDataKinds and -XPolyKinds instead                                                      
       [ 3 of 29] Compiling Data.Functor.Contravariant.Divise                                                                       
                                                                                                                                    
       /var/stackage/work/unpack-dir/unpacked/functor-combinators-0.4.1.2-189bc904b94ae0300bfe91d3eef4c9369d41069786b5f02554422211b4
7ba7c9/src/Data/Functor/Contravariant/Divise.hs:29:1: error:                                                                        
           Could not find module ‘Control.Monad.Trans.Error’                                                                        
           Perhaps you meant                                                                                                        
             Control.Monad.Trans.Free (from free-5.2)                                                                               
             Control.Monad.Trans.Iter (from free-5.2)                                                                               
             Control.Monad.Trans.Either (needs flag -package-id transformers-either-0.1.4)                                          
           Use -v (or `:set -v` in ghci) to see a list of the files searched for.                                                   
          |
       29 | import           Control.Monad.Trans.Error
          | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        
       /var/stackage/work/unpack-dir/unpacked/functor-combinators-0.4.1.2-189bc904b94ae0300bfe91d3eef4c9369d41069786b5f02554422211b4
7ba7c9/src/Data/Functor/Contravariant/Divise.hs:32:1: error:
           Could not find module ‘Control.Monad.Trans.List’
           Perhaps you meant
             Control.Monad.Trans.Has (needs flag -package-id has-transformers-0.1.0.4)
             Control.Monad.Trans.Cont (needs flag -package-id rerebase-1.20)
             Control.Monad.Trans.Cont (from transformers-0.6.1.0)
           Use -v (or `:set -v` in ghci) to see a list of the files searched for.
          |
       32 | import           Control.Monad.Trans.List
          | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by mstksg** [comment]
thanks, should be fixed as of 0.4.1.3
